general.import = [ "~/.config/alacritty/catppuccin.toml"]

[window]
opacity = 0.95
padding = { x = 15, y = 10 }

# [colors.primary]
# background = '#181616'
# foreground = '#c5c9c5'


[keyboard]
bindings = [
    # example
    # { key = "d", mods = "Control", action = "None" }
]
