#!/usr/bin/env bash

# Source:
# https://github.com/MariaSolOs/dotfiles/blob/3122853afa7d86b5bd0bfc202a5f08fee77c0787/.local/bin/buildnvim.sh

set -x
set -eo pipefail

function buildnvim() {
    # Make sure I cloned the thing.
    local nvim_dir="$HOME/git/neovim"

    if [ -d "$nvim_dir" ]; then
        cd "$nvim_dir"
        git checkout master
        git pull
    else
        mkdir -p "$nvim_dir"
        git clone https://github.com/neovim/neovim "$nvim_dir"
        cd "$nvim_dir"
    fi

    # Go back to the given commit or HEAD.
    local commit="${1:-HEAD}"
    printf '\n========== CHECKING OUT COMMIT %s... ==========\n' "$commit"
    git reset --hard "$commit"

    # Apply my fold column patch.
    printf '\n========== APPLYING FOLDCOLUMN PATCH... ==========\n'
    local patch_file="$nvim_dir/foldcolumn.patch"
    cat <<'EOF' >"$patch_file"
diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
index 5196d5c9f4..ba336713cf 100644
--- a/src/nvim/drawline.c
+++ b/src/nvim/drawline.c
@@ -443,10 +443,8 @@ void fill_foldcolumn(win_T *wp, foldinfo_T foldinfo, linenr_T lnum, int attr, in
       symbol = wp->w_p_fcs_chars.foldopen;
     } else if (first_level == 1) {
       symbol = wp->w_p_fcs_chars.foldsep;
-    } else if (first_level + i <= 9) {
-      symbol = schar_from_ascii('0' + first_level + i);
     } else {
-      symbol = schar_from_ascii('>');
+      symbol = schar_from_ascii(' ');
     }

     int vcol = i >= level ? -1 : (i == closedcol - 1 && closed) ? -2 : -3;
EOF
    git apply "$patch_file"
    rm -f "$patch_file"

    # Build.& Install
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    sudo make install

    # Remove the patched changes.
    git checkout .
}

buildnvim "$@"
