return {}
-- return {
--     "saghen/blink.cmp",
--     -- optional: provides snippets for the snippet source
--     dependencies = {
--         "L3MON4D3/LuaSnip",
--         "tronikelis/blink-cmp-ctags",
--     },
--     event = { "InsertEnter" },
--
--     -- use a release tag to download pre-built binaries
--     version = "1.*",
--     -- AND/OR build from source, requires nightly: https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust
--     -- build = 'cargo build --release',
--
--     ---@module 'blink.cmp'
--     opts = {
--         -- See :h blink-cmp-config-keymap for defining your own keymap
--         keymap = {
--             preset = "none",
--             ["<C-e>"] = { "hide" },
--             ["<C-y>"] = { "select_and_accept" },
--             ["<C-p>"] = { "select_prev", "fallback_to_mappings" },
--             ["<C-n>"] = { "show", "select_next", "fallback_to_mappings" },
--             ["<C-b>"] = { "scroll_documentation_up", "fallback" },
--             ["<C-f>"] = { "scroll_documentation_down", "fallback" },
--             ["<C-k>"] = { "show_signature", "hide_signature", "fallback" },
--             ["<Tab>"] = { "snippet_forward", "fallback" },
--         },
--
--         completion = {
--             list = {
--                 -- Insert items while navigating the completion list.
--                 selection = { preselect = false, auto_insert = true },
--                 max_items = 15,
--             },
--             documentation = { auto_show = false },
--             menu = { auto_show = false, scrollbar = false },
--         },
--         snippets = { preset = "luasnip" },
--
--         -- Disable command line completion:
--         -- cmdline = { enabled = false },
--
--         -- Default list of enabled providers defined so that you can extend it
--         -- elsewhere in your config, without redefining it, due to `opts_extend`
--         sources = {
--             -- default = { "lsp", "path", "snippets", "buffer" },
--             default = { "path", "snippets", "buffer", "ctags" },
--             providers = {
--                 lsp = { fallbacks = { "ctags" } },
--                 ctags = {
--                     name = "Ctags",
--                     module = "blink-ctags",
--                 },
--             },
--         },
--
--         appearance = {
--             kind_icons = require("icons").symbol_kinds,
--         },
--
--         -- (Default) Rust fuzzy matcher for typo resistance and significantly better performance
--         -- You may use a lua implementation instead by using `implementation = "lua"` or fallback to the lua implementation,
--         -- when the Rust fuzzy matcher is not available, by using `implementation = "prefer_rust"`
--         fuzzy = { implementation = "prefer_rust_with_warning" },
--     },
--     config = function(_, opts)
--         require("blink.cmp").setup(opts)
--
--         -- Extend neovim's client capabilities with the completion ones.
--         vim.lsp.config("*", { capabilities = require("blink.cmp").get_lsp_capabilities(nil, true) })
--     end,
-- }
